/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Quote } from "./Quote";
import { QuoteCountArgs } from "./QuoteCountArgs";
import { QuoteFindManyArgs } from "./QuoteFindManyArgs";
import { QuoteFindUniqueArgs } from "./QuoteFindUniqueArgs";
import { CreateQuoteArgs } from "./CreateQuoteArgs";
import { UpdateQuoteArgs } from "./UpdateQuoteArgs";
import { DeleteQuoteArgs } from "./DeleteQuoteArgs";
import { Customer } from "../../customer/base/Customer";
import { Hauler } from "../../hauler/base/Hauler";
import { Product } from "../../product/base/Product";
import { SalesRep } from "../../salesRep/base/SalesRep";
import { TeamSupportRep } from "../../teamSupportRep/base/TeamSupportRep";
import { QuoteService } from "../quote.service";
@graphql.Resolver(() => Quote)
export class QuoteResolverBase {
  constructor(protected readonly service: QuoteService) {}

  async _quotesMeta(
    @graphql.Args() args: QuoteCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Quote])
  async quotes(@graphql.Args() args: QuoteFindManyArgs): Promise<Quote[]> {
    return this.service.quotes(args);
  }

  @graphql.Query(() => Quote, { nullable: true })
  async quote(
    @graphql.Args() args: QuoteFindUniqueArgs
  ): Promise<Quote | null> {
    const result = await this.service.quote(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Quote)
  async createQuote(@graphql.Args() args: CreateQuoteArgs): Promise<Quote> {
    return await this.service.createQuote({
      ...args,
      data: {
        ...args.data,

        customer: args.data.customer
          ? {
              connect: args.data.customer,
            }
          : undefined,

        hauler: args.data.hauler
          ? {
              connect: args.data.hauler,
            }
          : undefined,

        product: args.data.product
          ? {
              connect: args.data.product,
            }
          : undefined,

        salesRep: args.data.salesRep
          ? {
              connect: args.data.salesRep,
            }
          : undefined,

        teamSupportRep: args.data.teamSupportRep
          ? {
              connect: args.data.teamSupportRep,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Quote)
  async updateQuote(
    @graphql.Args() args: UpdateQuoteArgs
  ): Promise<Quote | null> {
    try {
      return await this.service.updateQuote({
        ...args,
        data: {
          ...args.data,

          customer: args.data.customer
            ? {
                connect: args.data.customer,
              }
            : undefined,

          hauler: args.data.hauler
            ? {
                connect: args.data.hauler,
              }
            : undefined,

          product: args.data.product
            ? {
                connect: args.data.product,
              }
            : undefined,

          salesRep: args.data.salesRep
            ? {
                connect: args.data.salesRep,
              }
            : undefined,

          teamSupportRep: args.data.teamSupportRep
            ? {
                connect: args.data.teamSupportRep,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Quote)
  async deleteQuote(
    @graphql.Args() args: DeleteQuoteArgs
  ): Promise<Quote | null> {
    try {
      return await this.service.deleteQuote(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Customer, {
    nullable: true,
    name: "customer",
  })
  async getCustomer(@graphql.Parent() parent: Quote): Promise<Customer | null> {
    const result = await this.service.getCustomer(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => Hauler, {
    nullable: true,
    name: "hauler",
  })
  async getHauler(@graphql.Parent() parent: Quote): Promise<Hauler | null> {
    const result = await this.service.getHauler(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => Product, {
    nullable: true,
    name: "product",
  })
  async getProduct(@graphql.Parent() parent: Quote): Promise<Product | null> {
    const result = await this.service.getProduct(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => SalesRep, {
    nullable: true,
    name: "salesRep",
  })
  async getSalesRep(@graphql.Parent() parent: Quote): Promise<SalesRep | null> {
    const result = await this.service.getSalesRep(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => TeamSupportRep, {
    nullable: true,
    name: "teamSupportRep",
  })
  async getTeamSupportRep(
    @graphql.Parent() parent: Quote
  ): Promise<TeamSupportRep | null> {
    const result = await this.service.getTeamSupportRep(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
